services:
  rdb:
    image: mysql:8.0
    container_name: mysql-jvm
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    ports:
      - 3306:3306
    platform: linux/x86_64
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:7.4.2
    container_name: redis-jvm
    ports:
      - 6379:6379
  redis-popular:
    image: redis:7.4.2
    container_name: redis-popular-jvm
    ports:
      - 6380:6379
  kafka:
    image: apache/kafka:3.8.0
    container_name: kafka-jvm
    ports:
      - 9092:9092

