
CREATE DATABASE IF NOT EXISTS `users`;
CREATE DATABASE IF NOT EXISTS `users_test`;
CREATE DATABASE IF NOT EXISTS `memo_service`;
CREATE DATABASE IF NOT EXISTS `memo_service_test`;
CREATE DATABASE IF NOT EXISTS `board_service`;
CREATE DATABASE IF NOT EXISTS `board_service_test`;
