server:
  port: 8080
#
#logging:
#  level:
#    root: DEBUG
#    org.springframework: DEBUG

spring:
  application:
    name: msa-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      globalcors:
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowedOrigins: 'http://localhost:3000'
            allowedHeaders: '*'
            allowedMethods:
            - GET
            - POST
            - DELETE
            - PUT
            - PATCH
            - OPTIONS
      routes:
        - id: memo-service
          uri: http://127.0.0.1:8082
          predicates:
            - Path=/memo-service/**
          filters:
            - RewritePath=/memo-service/(?<segment>.*), /$\{segment}
        - id: auth-service
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/auth-service/**
          filters:
            - RewritePath=/auth-service/(?<segment>.*), /$\{segment}
        - id: board-service
          uri: http://127.0.0.1:8083
          predicates:
            - Path=/board-service/**
          filters:
            - RewritePath=/board-service/(?<segment>.*), /$\{segment}
